### ISSUE TITLE
Feature: Add Unit test and increase ci coverage.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1233]
To more adapt release circle, we need more test codes to ensure new features/bugfixes not affect exists code and/or process.

Todo list:

<del>

- [x] add code coverage codes in ci progress. example: 
```shell
go test -coverprofile=coverage.txt -covermode count `go list ./... | grep -v tests` -v 2>&1 | tee test_output.txt
cat test_output.txt | go-junit-report > report.xml
gocover-cobertura < coverage.txt > coverage.xml
gocov convert coverage.txt | gocov report
```

</del>

- [ ] fix failed tests
- [ ] add more unit test. files like below:
* `pkg/utils`
* `pkg/remote`
* ...

**Comment by cuisongliu** [comment]
The actions can add a test coverage test.
