### ISSUE TITLE
Feature:  Add doc to spec Dev environment.

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1241]
Need Add docs to spec how to build test envs to start build/test/debug sealos it self.

Suggestions:
- [ ] add `.devcontainer` supportted by github
- [ ] add doc to spec which packages need to install before start like `libgpgme-dev,`libdevmapper-dev` and so on.
- [ ] TODO: Provide one `sleaos`'s cloud-based environment to quickly start coding.
