### ISSUE TITLE
sealos cloud provider roadmap

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2166]
- [ ] support public cloud
   - [ ] aws
   - [ ] alicloud
   - [ ] huawei
   - [ ] tengxun
   - [ ] azure
   - [ ] google 
- [ ] support to reconcile instance count
- [ ] support to reconcile vm images
- [ ] support to reconcile vm flavor
- [ ] support to reconcile volumes
- [x] using finalizer delete vms when delete CR https://github.com/labring/sealos/issues/2123
- [x] delete keypaire
- [ ] https://github.com/labring/sealos/blob/main/controllers/infra/drivers/aws/create_instance.go#L43 different image has different username
- [ ] make a virtual image to improve cluster creation performance, the image already install sealos and pull kubernetes base images
- [ ] e2e tests
- [ ] GC, stop vm if there is no corresponding CR in the cluster
- [ ] User guide docs
- [ ] CI auto deploy to cloud.sealos.io
- [ ] cloud terminal to ssh into the hosts
- [ ]  cloud terminal to the apiserver, copy kubeconfig to the terminal pod.
- [ ] show infra and cluster events
