### ISSUE TITLE
sealos core roadmap

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2210]
- [ ] user default kubeconfig apiserver set to https://cloud.sealos.io:6443, add cloud.sealos.io to default cert sans
- [ ] switch user namespace
- [ ] invite user into namespace
- [ ] create new namespace, conflict.
