### ISSUE TITLE
sealos cloud terminal roadmap

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2211]
- [ ] run terminal in user namespace
- [ ] terminal rootfs mount disks
- [ ] run multiple terminals
- [ ] cloud provider and pgsql or other applications can open its own client terminal
- [ ] add helm in terminal

**Comment by lingdie** [comment]
Can terminal have syntax highlighting?
