### ISSUE TITLE
sealos app store roadmap

### ISSUE THREAD

**Issue by fanux** [labring/sealos#2212]
- [ ] image list
- [ ] image details
- [ ] install app
- [ ] org management
- [ ] user management
- [ ] push image
- [ ] pull image
- [ ] auth module

---
- [ ] dispaly image-cr when using sealos push image
- [ ] organization creation and management
- [ ] private repository management

**Comment by fanux** [comment]
https://github.com/labring/sealos/issues/2454
