### ISSUE TITLE
Feature: release 4.2 roadmap

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2632]
- [x] Bugfix p2 (https://github.com/labring/sealos/issues?q=is%3Aopen+is%3Aissue+milestone%3Arelease-v4.2.0)
- [x] Test ci p1
- [ ] Apply  idempotent
- [ ] https://github.com/labring/sealos/issues/2560 Join  support amd64+arm64
- [ ] https://github.com/labring/sealos/issues/1154

**Comment by chenshengshi** [comment]
啥时候发布呀

**Comment by cuisongliu** [comment]
> 啥时候发布呀

预计1-2个月了，这月底会先发布4.1.5.
